apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-postgresql-0
  labels:
    type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
