apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow.fullname" . }}-env-secret
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.backendStore.postgres.enabled }}
  PGUSER: {{ required "postgres user must be specified" .Values.backendStore.postgres.user | b64enc }}
  PGPASSWORD: {{ required "postgres password must be specified" .Values.backendStore.postgres.password | b64enc }}
{{- end }}
{{- if .Values.artifactRoot.s3.enabled }}
{{- if and .Values.artifactRoot.s3.awsAccessKeyId .Values.artifactRoot.s3.awsSecretAccessKey }}
  AWS_ACCESS_KEY_ID: {{ .Values.artifactRoot.s3.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.artifactRoot.s3.awsSecretAccessKey | b64enc }}
{{- end }}
{{- end }}